name: Build Images
on: [ push ]
env:
  DOCKER_VERSION_FULL: "4.99.4"
  DOCKER_VERSION_MINOR: "4.99"
  DOCKER_VERSION_MAJOR: "4"
  PACKAGE_PREFIX: "+dfsg+really4.12.0-1build1"
jobs:

  images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build and push calibre
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            thibaultmorin/calibre:${{ env.DOCKER_VERSION_MAJOR }}
            thibaultmorin/calibre:${{ env.DOCKER_VERSION_MINOR }}
            thibaultmorin/calibre:${{ env.DOCKER_VERSION_FULL }}
          build-args: |
            version=${{ env.DOCKER_VERSION_FULL }}
            prefix=${{ env.PACKAGE_PREFIX }}
            git_sha=${{ github.sha }}
